// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: creation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Creation {

  /// <summary>Holder for reflection information generated from creation.proto</summary>
  public static partial class CreationReflection {

    #region Descriptor
    /// <summary>File descriptor for creation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5jcmVhdGlvbi5wcm90bxIIY3JlYXRpb24iIwoSR2V0Q3JlYXRpb25SZXF1",
            "ZXN0Eg0KBXRoZW1lGAEgASgJIj0KFVVwZGF0ZUNyZWF0aW9uUmVxdWVzdBIk",
            "CghjcmVhdGlvbhgBIAEoCzISLmNyZWF0aW9uLkNyZWF0aW9uIn4KDUNyZWF0",
            "aW9uUHJvcHMSDwoHc2xvdHRlZBgBIAEoCRIOCgZoZWFsdGgYAiABKAUSDAoE",
            "bW9vZBgDIAEoCRIOCgZodW5ncnkYBCABKAUSCwoDYWdlGAUgASgFEgwKBHJh",
            "bmsYBiABKAUSEwoLYWNoaWV2ZW1lbnQYByABKAkinAMKCENyZWF0aW9uEhUK",
            "DW1vZGVsX3ZlcnNpb24YASABKAkSEwoLY3JlYXRpb25faWQYAiABKAkSFQoN",
            "Y3JlYXRpb25fdHlwZRgDIAEoCRITCgtwcmVmYWJfdHlwZRgEIAEoCRIQCgh0",
            "ZW1wbGF0ZRgFIAEoCRIMCgRuYW1lGAYgASgJEhMKC2Rlc2NyaXB0aW9uGAcg",
            "ASgJEhAKCGNhdGVnb3J5GAggASgJEigKCXJlc291cmNlcxgJIAMoCzIVLmNy",
            "ZWF0aW9uLkNyZWF0aW9uUmVzEg0KBXNsb3RzGAogAygJEiYKBXByb3BzGAsg",
            "ASgLMhcuY3JlYXRpb24uQ3JlYXRpb25Qcm9wcxI3CgtleHRyYV9wcm9wcxgM",
            "IAMoCzIiLmNyZWF0aW9uLkNyZWF0aW9uLkV4dHJhUHJvcHNFbnRyeRIkCghj",
            "aGlsZHJlbhgNIAMoCzISLmNyZWF0aW9uLkNyZWF0aW9uGjEKD0V4dHJhUHJv",
            "cHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIigKC0Ny",
            "ZWF0aW9uUmVzEgwKBHR5cGUYASABKAkSCwoDdXJsGAIgASgJMlMKEENyZWF0",
            "aW9uUHJvdmlkZXISPwoLR2V0Q3JlYXRpb24SHC5jcmVhdGlvbi5HZXRDcmVh",
            "dGlvblJlcXVlc3QaEi5jcmVhdGlvbi5DcmVhdGlvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.GetCreationRequest), global::Creation.GetCreationRequest.Parser, new[]{ "Theme" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.UpdateCreationRequest), global::Creation.UpdateCreationRequest.Parser, new[]{ "Creation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.CreationProps), global::Creation.CreationProps.Parser, new[]{ "Slotted", "Health", "Mood", "Hungry", "Age", "Rank", "Achievement" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.Creation), global::Creation.Creation.Parser, new[]{ "ModelVersion", "CreationId", "CreationType", "PrefabType", "Template", "Name", "Description", "Category", "Resources", "Slots", "Props", "ExtraProps", "Children" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.CreationRes), global::Creation.CreationRes.Parser, new[]{ "Type", "Url" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetCreationRequest : pb::IMessage<GetCreationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCreationRequest> _parser = new pb::MessageParser<GetCreationRequest>(() => new GetCreationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCreationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest(GetCreationRequest other) : this() {
      theme_ = other.theme_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest Clone() {
      return new GetCreationRequest(this);
    }

    /// <summary>Field number for the "theme" field.</summary>
    public const int ThemeFieldNumber = 1;
    private string theme_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Theme {
      get { return theme_; }
      set {
        theme_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCreationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCreationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Theme != other.Theme) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Theme.Length != 0) hash ^= Theme.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Theme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Theme);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Theme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Theme);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Theme.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Theme);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCreationRequest other) {
      if (other == null) {
        return;
      }
      if (other.Theme.Length != 0) {
        Theme = other.Theme;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Theme = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Theme = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpdateCreationRequest : pb::IMessage<UpdateCreationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateCreationRequest> _parser = new pb::MessageParser<UpdateCreationRequest>(() => new UpdateCreationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateCreationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest(UpdateCreationRequest other) : this() {
      creation_ = other.creation_ != null ? other.creation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest Clone() {
      return new UpdateCreationRequest(this);
    }

    /// <summary>Field number for the "creation" field.</summary>
    public const int CreationFieldNumber = 1;
    private global::Creation.Creation creation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Creation.Creation Creation {
      get { return creation_; }
      set {
        creation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateCreationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateCreationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Creation, other.Creation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (creation_ != null) hash ^= Creation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (creation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Creation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (creation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Creation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (creation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Creation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateCreationRequest other) {
      if (other == null) {
        return;
      }
      if (other.creation_ != null) {
        if (creation_ == null) {
          Creation = new global::Creation.Creation();
        }
        Creation.MergeFrom(other.Creation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (creation_ == null) {
              Creation = new global::Creation.Creation();
            }
            input.ReadMessage(Creation);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (creation_ == null) {
              Creation = new global::Creation.Creation();
            }
            input.ReadMessage(Creation);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreationProps : pb::IMessage<CreationProps>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreationProps> _parser = new pb::MessageParser<CreationProps>(() => new CreationProps());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreationProps> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationProps() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationProps(CreationProps other) : this() {
      slotted_ = other.slotted_;
      health_ = other.health_;
      mood_ = other.mood_;
      hungry_ = other.hungry_;
      age_ = other.age_;
      rank_ = other.rank_;
      achievement_ = other.achievement_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationProps Clone() {
      return new CreationProps(this);
    }

    /// <summary>Field number for the "slotted" field.</summary>
    public const int SlottedFieldNumber = 1;
    private string slotted_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Slotted {
      get { return slotted_; }
      set {
        slotted_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "health" field.</summary>
    public const int HealthFieldNumber = 2;
    private int health_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Health {
      get { return health_; }
      set {
        health_ = value;
      }
    }

    /// <summary>Field number for the "mood" field.</summary>
    public const int MoodFieldNumber = 3;
    private string mood_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mood {
      get { return mood_; }
      set {
        mood_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hungry" field.</summary>
    public const int HungryFieldNumber = 4;
    private int hungry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hungry {
      get { return hungry_; }
      set {
        hungry_ = value;
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 5;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 6;
    private int rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "achievement" field.</summary>
    public const int AchievementFieldNumber = 7;
    private string achievement_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Achievement {
      get { return achievement_; }
      set {
        achievement_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreationProps);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreationProps other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Slotted != other.Slotted) return false;
      if (Health != other.Health) return false;
      if (Mood != other.Mood) return false;
      if (Hungry != other.Hungry) return false;
      if (Age != other.Age) return false;
      if (Rank != other.Rank) return false;
      if (Achievement != other.Achievement) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Slotted.Length != 0) hash ^= Slotted.GetHashCode();
      if (Health != 0) hash ^= Health.GetHashCode();
      if (Mood.Length != 0) hash ^= Mood.GetHashCode();
      if (Hungry != 0) hash ^= Hungry.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Rank != 0) hash ^= Rank.GetHashCode();
      if (Achievement.Length != 0) hash ^= Achievement.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Slotted.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Slotted);
      }
      if (Health != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Health);
      }
      if (Mood.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mood);
      }
      if (Hungry != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hungry);
      }
      if (Age != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Age);
      }
      if (Rank != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Rank);
      }
      if (Achievement.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Achievement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Slotted.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Slotted);
      }
      if (Health != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Health);
      }
      if (Mood.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mood);
      }
      if (Hungry != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hungry);
      }
      if (Age != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Age);
      }
      if (Rank != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Rank);
      }
      if (Achievement.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Achievement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Slotted.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Slotted);
      }
      if (Health != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Health);
      }
      if (Mood.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mood);
      }
      if (Hungry != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hungry);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (Rank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rank);
      }
      if (Achievement.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Achievement);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreationProps other) {
      if (other == null) {
        return;
      }
      if (other.Slotted.Length != 0) {
        Slotted = other.Slotted;
      }
      if (other.Health != 0) {
        Health = other.Health;
      }
      if (other.Mood.Length != 0) {
        Mood = other.Mood;
      }
      if (other.Hungry != 0) {
        Hungry = other.Hungry;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      if (other.Achievement.Length != 0) {
        Achievement = other.Achievement;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Slotted = input.ReadString();
            break;
          }
          case 16: {
            Health = input.ReadInt32();
            break;
          }
          case 26: {
            Mood = input.ReadString();
            break;
          }
          case 32: {
            Hungry = input.ReadInt32();
            break;
          }
          case 40: {
            Age = input.ReadInt32();
            break;
          }
          case 48: {
            Rank = input.ReadInt32();
            break;
          }
          case 58: {
            Achievement = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Slotted = input.ReadString();
            break;
          }
          case 16: {
            Health = input.ReadInt32();
            break;
          }
          case 26: {
            Mood = input.ReadString();
            break;
          }
          case 32: {
            Hungry = input.ReadInt32();
            break;
          }
          case 40: {
            Age = input.ReadInt32();
            break;
          }
          case 48: {
            Rank = input.ReadInt32();
            break;
          }
          case 58: {
            Achievement = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Creation : pb::IMessage<Creation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Creation> _parser = new pb::MessageParser<Creation>(() => new Creation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Creation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation(Creation other) : this() {
      modelVersion_ = other.modelVersion_;
      creationId_ = other.creationId_;
      creationType_ = other.creationType_;
      prefabType_ = other.prefabType_;
      template_ = other.template_;
      name_ = other.name_;
      description_ = other.description_;
      category_ = other.category_;
      resources_ = other.resources_.Clone();
      slots_ = other.slots_.Clone();
      props_ = other.props_ != null ? other.props_.Clone() : null;
      extraProps_ = other.extraProps_.Clone();
      children_ = other.children_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation Clone() {
      return new Creation(this);
    }

    /// <summary>Field number for the "model_version" field.</summary>
    public const int ModelVersionFieldNumber = 1;
    private string modelVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ModelVersion {
      get { return modelVersion_; }
      set {
        modelVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creation_id" field.</summary>
    public const int CreationIdFieldNumber = 2;
    private string creationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CreationId {
      get { return creationId_; }
      set {
        creationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creation_type" field.</summary>
    public const int CreationTypeFieldNumber = 3;
    private string creationType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CreationType {
      get { return creationType_; }
      set {
        creationType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefab_type" field.</summary>
    public const int PrefabTypeFieldNumber = 4;
    private string prefabType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PrefabType {
      get { return prefabType_; }
      set {
        prefabType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "template" field.</summary>
    public const int TemplateFieldNumber = 5;
    private string template_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Template {
      get { return template_; }
      set {
        template_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 6;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 7;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 8;
    private string category_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Category {
      get { return category_; }
      set {
        category_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Creation.CreationRes> _repeated_resources_codec
        = pb::FieldCodec.ForMessage(74, global::Creation.CreationRes.Parser);
    private readonly pbc::RepeatedField<global::Creation.CreationRes> resources_ = new pbc::RepeatedField<global::Creation.CreationRes>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Creation.CreationRes> Resources {
      get { return resources_; }
    }

    /// <summary>Field number for the "slots" field.</summary>
    public const int SlotsFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_slots_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> slots_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Slots {
      get { return slots_; }
    }

    /// <summary>Field number for the "props" field.</summary>
    public const int PropsFieldNumber = 11;
    private global::Creation.CreationProps props_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Creation.CreationProps Props {
      get { return props_; }
      set {
        props_ = value;
      }
    }

    /// <summary>Field number for the "extra_props" field.</summary>
    public const int ExtraPropsFieldNumber = 12;
    private static readonly pbc::MapField<string, string>.Codec _map_extraProps_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 98);
    private readonly pbc::MapField<string, string> extraProps_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> ExtraProps {
      get { return extraProps_; }
    }

    /// <summary>Field number for the "children" field.</summary>
    public const int ChildrenFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Creation.Creation> _repeated_children_codec
        = pb::FieldCodec.ForMessage(106, global::Creation.Creation.Parser);
    private readonly pbc::RepeatedField<global::Creation.Creation> children_ = new pbc::RepeatedField<global::Creation.Creation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Creation.Creation> Children {
      get { return children_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Creation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Creation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ModelVersion != other.ModelVersion) return false;
      if (CreationId != other.CreationId) return false;
      if (CreationType != other.CreationType) return false;
      if (PrefabType != other.PrefabType) return false;
      if (Template != other.Template) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Category != other.Category) return false;
      if(!resources_.Equals(other.resources_)) return false;
      if(!slots_.Equals(other.slots_)) return false;
      if (!object.Equals(Props, other.Props)) return false;
      if (!ExtraProps.Equals(other.ExtraProps)) return false;
      if(!children_.Equals(other.children_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ModelVersion.Length != 0) hash ^= ModelVersion.GetHashCode();
      if (CreationId.Length != 0) hash ^= CreationId.GetHashCode();
      if (CreationType.Length != 0) hash ^= CreationType.GetHashCode();
      if (PrefabType.Length != 0) hash ^= PrefabType.GetHashCode();
      if (Template.Length != 0) hash ^= Template.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Category.Length != 0) hash ^= Category.GetHashCode();
      hash ^= resources_.GetHashCode();
      hash ^= slots_.GetHashCode();
      if (props_ != null) hash ^= Props.GetHashCode();
      hash ^= ExtraProps.GetHashCode();
      hash ^= children_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ModelVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ModelVersion);
      }
      if (CreationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CreationId);
      }
      if (CreationType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationType);
      }
      if (PrefabType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PrefabType);
      }
      if (Template.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Template);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Description);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Category);
      }
      resources_.WriteTo(output, _repeated_resources_codec);
      slots_.WriteTo(output, _repeated_slots_codec);
      if (props_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Props);
      }
      extraProps_.WriteTo(output, _map_extraProps_codec);
      children_.WriteTo(output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ModelVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ModelVersion);
      }
      if (CreationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CreationId);
      }
      if (CreationType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationType);
      }
      if (PrefabType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PrefabType);
      }
      if (Template.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Template);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Description);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Category);
      }
      resources_.WriteTo(ref output, _repeated_resources_codec);
      slots_.WriteTo(ref output, _repeated_slots_codec);
      if (props_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Props);
      }
      extraProps_.WriteTo(ref output, _map_extraProps_codec);
      children_.WriteTo(ref output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ModelVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelVersion);
      }
      if (CreationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationId);
      }
      if (CreationType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationType);
      }
      if (PrefabType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrefabType);
      }
      if (Template.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Template);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Category.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      size += resources_.CalculateSize(_repeated_resources_codec);
      size += slots_.CalculateSize(_repeated_slots_codec);
      if (props_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Props);
      }
      size += extraProps_.CalculateSize(_map_extraProps_codec);
      size += children_.CalculateSize(_repeated_children_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Creation other) {
      if (other == null) {
        return;
      }
      if (other.ModelVersion.Length != 0) {
        ModelVersion = other.ModelVersion;
      }
      if (other.CreationId.Length != 0) {
        CreationId = other.CreationId;
      }
      if (other.CreationType.Length != 0) {
        CreationType = other.CreationType;
      }
      if (other.PrefabType.Length != 0) {
        PrefabType = other.PrefabType;
      }
      if (other.Template.Length != 0) {
        Template = other.Template;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Category.Length != 0) {
        Category = other.Category;
      }
      resources_.Add(other.resources_);
      slots_.Add(other.slots_);
      if (other.props_ != null) {
        if (props_ == null) {
          Props = new global::Creation.CreationProps();
        }
        Props.MergeFrom(other.Props);
      }
      extraProps_.Add(other.extraProps_);
      children_.Add(other.children_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ModelVersion = input.ReadString();
            break;
          }
          case 18: {
            CreationId = input.ReadString();
            break;
          }
          case 26: {
            CreationType = input.ReadString();
            break;
          }
          case 34: {
            PrefabType = input.ReadString();
            break;
          }
          case 42: {
            Template = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 58: {
            Description = input.ReadString();
            break;
          }
          case 66: {
            Category = input.ReadString();
            break;
          }
          case 74: {
            resources_.AddEntriesFrom(input, _repeated_resources_codec);
            break;
          }
          case 82: {
            slots_.AddEntriesFrom(input, _repeated_slots_codec);
            break;
          }
          case 90: {
            if (props_ == null) {
              Props = new global::Creation.CreationProps();
            }
            input.ReadMessage(Props);
            break;
          }
          case 98: {
            extraProps_.AddEntriesFrom(input, _map_extraProps_codec);
            break;
          }
          case 106: {
            children_.AddEntriesFrom(input, _repeated_children_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ModelVersion = input.ReadString();
            break;
          }
          case 18: {
            CreationId = input.ReadString();
            break;
          }
          case 26: {
            CreationType = input.ReadString();
            break;
          }
          case 34: {
            PrefabType = input.ReadString();
            break;
          }
          case 42: {
            Template = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 58: {
            Description = input.ReadString();
            break;
          }
          case 66: {
            Category = input.ReadString();
            break;
          }
          case 74: {
            resources_.AddEntriesFrom(ref input, _repeated_resources_codec);
            break;
          }
          case 82: {
            slots_.AddEntriesFrom(ref input, _repeated_slots_codec);
            break;
          }
          case 90: {
            if (props_ == null) {
              Props = new global::Creation.CreationProps();
            }
            input.ReadMessage(Props);
            break;
          }
          case 98: {
            extraProps_.AddEntriesFrom(ref input, _map_extraProps_codec);
            break;
          }
          case 106: {
            children_.AddEntriesFrom(ref input, _repeated_children_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreationRes : pb::IMessage<CreationRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreationRes> _parser = new pb::MessageParser<CreationRes>(() => new CreationRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreationRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes(CreationRes other) : this() {
      type_ = other.type_;
      url_ = other.url_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes Clone() {
      return new CreationRes(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreationRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreationRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Url != other.Url) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreationRes other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
