// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: creation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Creation {

  /// <summary>Holder for reflection information generated from creation.proto</summary>
  public static partial class CreationReflection {

    #region Descriptor
    /// <summary>File descriptor for creation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5jcmVhdGlvbi5wcm90bxIIY3JlYXRpb24iIwoSR2V0Q3JlYXRpb25SZXF1",
            "ZXN0Eg0KBXdvcmxkGAEgASgJIj0KFVVwZGF0ZUNyZWF0aW9uUmVxdWVzdBIk",
            "CghjcmVhdGlvbhgBIAEoCzISLmNyZWF0aW9uLkNyZWF0aW9uIuoDCghDcmVh",
            "dGlvbhIWCg5zY2hlbWFfdmVyc2lvbhgBIAEoCRIKCgJpZBgCIAEoCRIQCghx",
            "dWFudGl0eRgDIAEoBRIOCgZzdGF0dXMYBCABKAkSFQoNY3JlYXRpb25fdHlw",
            "ZRgFIAEoCRITCgtwcmVmYWJfdHlwZRgGIAEoCRIQCgh0ZW1wbGF0ZRgHIAEo",
            "CRIMCgRuYW1lGAggASgJEhMKC2Rlc2NyaXB0aW9uGAkgASgJEhAKCGNhdGVn",
            "b3J5GAogASgJEigKCXJlc291cmNlcxgLIAMoCzIVLmNyZWF0aW9uLkNyZWF0",
            "aW9uUmVzEg0KBXNsb3RzGAwgAygJEiwKBWF0dHJzGA0gAygLMh0uY3JlYXRp",
            "b24uQ3JlYXRpb24uQXR0cnNFbnRyeRI3CgtleHRyYV9wcm9wcxgOIAMoCzIi",
            "LmNyZWF0aW9uLkNyZWF0aW9uLkV4dHJhUHJvcHNFbnRyeRIkCghjaGlsZHJl",
            "bhgPIAMoCzISLmNyZWF0aW9uLkNyZWF0aW9uGiwKCkF0dHJzRW50cnkSCwoD",
            "a2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARoxCg9FeHRyYVByb3BzRW50",
            "cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIoCgtDcmVhdGlv",
            "blJlcxIMCgR0eXBlGAEgASgJEgsKA3VybBgCIAEoCTJTChBDcmVhdGlvblBy",
            "b3ZpZGVyEj8KC0dldENyZWF0aW9uEhwuY3JlYXRpb24uR2V0Q3JlYXRpb25S",
            "ZXF1ZXN0GhIuY3JlYXRpb24uQ3JlYXRpb25iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.GetCreationRequest), global::Creation.GetCreationRequest.Parser, new[]{ "World" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.UpdateCreationRequest), global::Creation.UpdateCreationRequest.Parser, new[]{ "Creation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.Creation), global::Creation.Creation.Parser, new[]{ "SchemaVersion", "Id", "Quantity", "Status", "CreationType", "PrefabType", "Template", "Name", "Description", "Category", "Resources", "Slots", "Attrs", "ExtraProps", "Children" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Creation.CreationRes), global::Creation.CreationRes.Parser, new[]{ "Type", "Url" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetCreationRequest : pb::IMessage<GetCreationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCreationRequest> _parser = new pb::MessageParser<GetCreationRequest>(() => new GetCreationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCreationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest(GetCreationRequest other) : this() {
      world_ = other.world_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCreationRequest Clone() {
      return new GetCreationRequest(this);
    }

    /// <summary>Field number for the "world" field.</summary>
    public const int WorldFieldNumber = 1;
    private string world_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string World {
      get { return world_; }
      set {
        world_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCreationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCreationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (World != other.World) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (World.Length != 0) hash ^= World.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (World.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(World);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (World.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(World);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (World.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(World);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCreationRequest other) {
      if (other == null) {
        return;
      }
      if (other.World.Length != 0) {
        World = other.World;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            World = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            World = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpdateCreationRequest : pb::IMessage<UpdateCreationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateCreationRequest> _parser = new pb::MessageParser<UpdateCreationRequest>(() => new UpdateCreationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateCreationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest(UpdateCreationRequest other) : this() {
      creation_ = other.creation_ != null ? other.creation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateCreationRequest Clone() {
      return new UpdateCreationRequest(this);
    }

    /// <summary>Field number for the "creation" field.</summary>
    public const int CreationFieldNumber = 1;
    private global::Creation.Creation creation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Creation.Creation Creation {
      get { return creation_; }
      set {
        creation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateCreationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateCreationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Creation, other.Creation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (creation_ != null) hash ^= Creation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (creation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Creation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (creation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Creation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (creation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Creation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateCreationRequest other) {
      if (other == null) {
        return;
      }
      if (other.creation_ != null) {
        if (creation_ == null) {
          Creation = new global::Creation.Creation();
        }
        Creation.MergeFrom(other.Creation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (creation_ == null) {
              Creation = new global::Creation.Creation();
            }
            input.ReadMessage(Creation);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (creation_ == null) {
              Creation = new global::Creation.Creation();
            }
            input.ReadMessage(Creation);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Creation : pb::IMessage<Creation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Creation> _parser = new pb::MessageParser<Creation>(() => new Creation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Creation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation(Creation other) : this() {
      schemaVersion_ = other.schemaVersion_;
      id_ = other.id_;
      quantity_ = other.quantity_;
      status_ = other.status_;
      creationType_ = other.creationType_;
      prefabType_ = other.prefabType_;
      template_ = other.template_;
      name_ = other.name_;
      description_ = other.description_;
      category_ = other.category_;
      resources_ = other.resources_.Clone();
      slots_ = other.slots_.Clone();
      attrs_ = other.attrs_.Clone();
      extraProps_ = other.extraProps_.Clone();
      children_ = other.children_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Creation Clone() {
      return new Creation(this);
    }

    /// <summary>Field number for the "schema_version" field.</summary>
    public const int SchemaVersionFieldNumber = 1;
    private string schemaVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SchemaVersion {
      get { return schemaVersion_; }
      set {
        schemaVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 3;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creation_type" field.</summary>
    public const int CreationTypeFieldNumber = 5;
    private string creationType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CreationType {
      get { return creationType_; }
      set {
        creationType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefab_type" field.</summary>
    public const int PrefabTypeFieldNumber = 6;
    private string prefabType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PrefabType {
      get { return prefabType_; }
      set {
        prefabType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "template" field.</summary>
    public const int TemplateFieldNumber = 7;
    private string template_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Template {
      get { return template_; }
      set {
        template_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 8;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 9;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 10;
    private string category_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Category {
      get { return category_; }
      set {
        category_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Creation.CreationRes> _repeated_resources_codec
        = pb::FieldCodec.ForMessage(90, global::Creation.CreationRes.Parser);
    private readonly pbc::RepeatedField<global::Creation.CreationRes> resources_ = new pbc::RepeatedField<global::Creation.CreationRes>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Creation.CreationRes> Resources {
      get { return resources_; }
    }

    /// <summary>Field number for the "slots" field.</summary>
    public const int SlotsFieldNumber = 12;
    private static readonly pb::FieldCodec<string> _repeated_slots_codec
        = pb::FieldCodec.ForString(98);
    private readonly pbc::RepeatedField<string> slots_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Slots {
      get { return slots_; }
    }

    /// <summary>Field number for the "attrs" field.</summary>
    public const int AttrsFieldNumber = 13;
    private static readonly pbc::MapField<string, string>.Codec _map_attrs_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 106);
    private readonly pbc::MapField<string, string> attrs_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Attrs {
      get { return attrs_; }
    }

    /// <summary>Field number for the "extra_props" field.</summary>
    public const int ExtraPropsFieldNumber = 14;
    private static readonly pbc::MapField<string, string>.Codec _map_extraProps_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 114);
    private readonly pbc::MapField<string, string> extraProps_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> ExtraProps {
      get { return extraProps_; }
    }

    /// <summary>Field number for the "children" field.</summary>
    public const int ChildrenFieldNumber = 15;
    private static readonly pb::FieldCodec<global::Creation.Creation> _repeated_children_codec
        = pb::FieldCodec.ForMessage(122, global::Creation.Creation.Parser);
    private readonly pbc::RepeatedField<global::Creation.Creation> children_ = new pbc::RepeatedField<global::Creation.Creation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Creation.Creation> Children {
      get { return children_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Creation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Creation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SchemaVersion != other.SchemaVersion) return false;
      if (Id != other.Id) return false;
      if (Quantity != other.Quantity) return false;
      if (Status != other.Status) return false;
      if (CreationType != other.CreationType) return false;
      if (PrefabType != other.PrefabType) return false;
      if (Template != other.Template) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Category != other.Category) return false;
      if(!resources_.Equals(other.resources_)) return false;
      if(!slots_.Equals(other.slots_)) return false;
      if (!Attrs.Equals(other.Attrs)) return false;
      if (!ExtraProps.Equals(other.ExtraProps)) return false;
      if(!children_.Equals(other.children_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SchemaVersion.Length != 0) hash ^= SchemaVersion.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (CreationType.Length != 0) hash ^= CreationType.GetHashCode();
      if (PrefabType.Length != 0) hash ^= PrefabType.GetHashCode();
      if (Template.Length != 0) hash ^= Template.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Category.Length != 0) hash ^= Category.GetHashCode();
      hash ^= resources_.GetHashCode();
      hash ^= slots_.GetHashCode();
      hash ^= Attrs.GetHashCode();
      hash ^= ExtraProps.GetHashCode();
      hash ^= children_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SchemaVersion);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Quantity != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Quantity);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Status);
      }
      if (CreationType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CreationType);
      }
      if (PrefabType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PrefabType);
      }
      if (Template.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Template);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Description);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Category);
      }
      resources_.WriteTo(output, _repeated_resources_codec);
      slots_.WriteTo(output, _repeated_slots_codec);
      attrs_.WriteTo(output, _map_attrs_codec);
      extraProps_.WriteTo(output, _map_extraProps_codec);
      children_.WriteTo(output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SchemaVersion);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Quantity != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Quantity);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Status);
      }
      if (CreationType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CreationType);
      }
      if (PrefabType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PrefabType);
      }
      if (Template.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Template);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Description);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Category);
      }
      resources_.WriteTo(ref output, _repeated_resources_codec);
      slots_.WriteTo(ref output, _repeated_slots_codec);
      attrs_.WriteTo(ref output, _map_attrs_codec);
      extraProps_.WriteTo(ref output, _map_extraProps_codec);
      children_.WriteTo(ref output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SchemaVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SchemaVersion);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (CreationType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationType);
      }
      if (PrefabType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrefabType);
      }
      if (Template.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Template);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Category.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      size += resources_.CalculateSize(_repeated_resources_codec);
      size += slots_.CalculateSize(_repeated_slots_codec);
      size += attrs_.CalculateSize(_map_attrs_codec);
      size += extraProps_.CalculateSize(_map_extraProps_codec);
      size += children_.CalculateSize(_repeated_children_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Creation other) {
      if (other == null) {
        return;
      }
      if (other.SchemaVersion.Length != 0) {
        SchemaVersion = other.SchemaVersion;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.CreationType.Length != 0) {
        CreationType = other.CreationType;
      }
      if (other.PrefabType.Length != 0) {
        PrefabType = other.PrefabType;
      }
      if (other.Template.Length != 0) {
        Template = other.Template;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Category.Length != 0) {
        Category = other.Category;
      }
      resources_.Add(other.resources_);
      slots_.Add(other.slots_);
      attrs_.Add(other.attrs_);
      extraProps_.Add(other.extraProps_);
      children_.Add(other.children_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SchemaVersion = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            Quantity = input.ReadInt32();
            break;
          }
          case 34: {
            Status = input.ReadString();
            break;
          }
          case 42: {
            CreationType = input.ReadString();
            break;
          }
          case 50: {
            PrefabType = input.ReadString();
            break;
          }
          case 58: {
            Template = input.ReadString();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
          case 74: {
            Description = input.ReadString();
            break;
          }
          case 82: {
            Category = input.ReadString();
            break;
          }
          case 90: {
            resources_.AddEntriesFrom(input, _repeated_resources_codec);
            break;
          }
          case 98: {
            slots_.AddEntriesFrom(input, _repeated_slots_codec);
            break;
          }
          case 106: {
            attrs_.AddEntriesFrom(input, _map_attrs_codec);
            break;
          }
          case 114: {
            extraProps_.AddEntriesFrom(input, _map_extraProps_codec);
            break;
          }
          case 122: {
            children_.AddEntriesFrom(input, _repeated_children_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SchemaVersion = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            Quantity = input.ReadInt32();
            break;
          }
          case 34: {
            Status = input.ReadString();
            break;
          }
          case 42: {
            CreationType = input.ReadString();
            break;
          }
          case 50: {
            PrefabType = input.ReadString();
            break;
          }
          case 58: {
            Template = input.ReadString();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
          case 74: {
            Description = input.ReadString();
            break;
          }
          case 82: {
            Category = input.ReadString();
            break;
          }
          case 90: {
            resources_.AddEntriesFrom(ref input, _repeated_resources_codec);
            break;
          }
          case 98: {
            slots_.AddEntriesFrom(ref input, _repeated_slots_codec);
            break;
          }
          case 106: {
            attrs_.AddEntriesFrom(ref input, _map_attrs_codec);
            break;
          }
          case 114: {
            extraProps_.AddEntriesFrom(ref input, _map_extraProps_codec);
            break;
          }
          case 122: {
            children_.AddEntriesFrom(ref input, _repeated_children_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreationRes : pb::IMessage<CreationRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreationRes> _parser = new pb::MessageParser<CreationRes>(() => new CreationRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreationRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Creation.CreationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes(CreationRes other) : this() {
      type_ = other.type_;
      url_ = other.url_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreationRes Clone() {
      return new CreationRes(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreationRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreationRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Url != other.Url) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreationRes other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
