// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: deviceinfo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Deviceinfo {
  public static partial class DeviceInfo
  {
    static readonly string __ServiceName = "deviceinfo.DeviceInfo";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Deviceinfo.DeviceInfoResponse> __Marshaller_deviceinfo_DeviceInfoResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Deviceinfo.DeviceInfoResponse.Parser));
    static readonly grpc::Marshaller<global::Deviceinfo.SetBindingStatusRequest> __Marshaller_deviceinfo_SetBindingStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Deviceinfo.SetBindingStatusRequest.Parser));
    static readonly grpc::Marshaller<global::Deviceinfo.SetBindingStatusResponse> __Marshaller_deviceinfo_SetBindingStatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Deviceinfo.SetBindingStatusResponse.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Deviceinfo.DeviceInfoResponse> __Method_GetDeviceInfo = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Deviceinfo.DeviceInfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDeviceInfo",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_deviceinfo_DeviceInfoResponse);

    static readonly grpc::Method<global::Deviceinfo.SetBindingStatusRequest, global::Deviceinfo.SetBindingStatusResponse> __Method_SetDeviceBindingStatus = new grpc::Method<global::Deviceinfo.SetBindingStatusRequest, global::Deviceinfo.SetBindingStatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetDeviceBindingStatus",
        __Marshaller_deviceinfo_SetBindingStatusRequest,
        __Marshaller_deviceinfo_SetBindingStatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Deviceinfo.DeviceinfoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DeviceInfo</summary>
    [grpc::BindServiceMethod(typeof(DeviceInfo), "BindService")]
    public abstract partial class DeviceInfoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Deviceinfo.DeviceInfoResponse> GetDeviceInfo(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Deviceinfo.SetBindingStatusResponse> SetDeviceBindingStatus(global::Deviceinfo.SetBindingStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DeviceInfo</summary>
    public partial class DeviceInfoClient : grpc::ClientBase<DeviceInfoClient>
    {
      /// <summary>Creates a new client for DeviceInfo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DeviceInfoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DeviceInfo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DeviceInfoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DeviceInfoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DeviceInfoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Deviceinfo.DeviceInfoResponse GetDeviceInfo(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDeviceInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Deviceinfo.DeviceInfoResponse GetDeviceInfo(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDeviceInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Deviceinfo.DeviceInfoResponse> GetDeviceInfoAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDeviceInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Deviceinfo.DeviceInfoResponse> GetDeviceInfoAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDeviceInfo, null, options, request);
      }
      public virtual global::Deviceinfo.SetBindingStatusResponse SetDeviceBindingStatus(global::Deviceinfo.SetBindingStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetDeviceBindingStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Deviceinfo.SetBindingStatusResponse SetDeviceBindingStatus(global::Deviceinfo.SetBindingStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetDeviceBindingStatus, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Deviceinfo.SetBindingStatusResponse> SetDeviceBindingStatusAsync(global::Deviceinfo.SetBindingStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetDeviceBindingStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Deviceinfo.SetBindingStatusResponse> SetDeviceBindingStatusAsync(global::Deviceinfo.SetBindingStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetDeviceBindingStatus, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DeviceInfoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DeviceInfoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DeviceInfoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetDeviceInfo, serviceImpl.GetDeviceInfo)
          .AddMethod(__Method_SetDeviceBindingStatus, serviceImpl.SetDeviceBindingStatus).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DeviceInfoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetDeviceInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Deviceinfo.DeviceInfoResponse>(serviceImpl.GetDeviceInfo));
      serviceBinder.AddMethod(__Method_SetDeviceBindingStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Deviceinfo.SetBindingStatusRequest, global::Deviceinfo.SetBindingStatusResponse>(serviceImpl.SetDeviceBindingStatus));
    }

  }
}
#endregion
